### PR TITLE
Replace translate3d with translate. Closes #21.

### LINKED ISSUE #21: Unnecessary use of translate3d causes subpixel font rendering issues
Using translate3d(-50%, 0, 0)
screen shot 2016-03-10 at 2 16 30 pm

Using translate(-50%, 0)
screen shot 2016-03-10 at 2 16 48 pm

### PR DESCRIPTION
**Pull request by josephdburdick**
This PR replaces instances of translate3d to translate transform. Sub-pixel rendering issue is resolved.

### CODE REVIEW

**Comment by josephdburdick** [comment]
@kazzkiq Rebased with master; merge conflicts resolved.

**Comment by josephdburdick** [comment]
By the way, I think the reason why there are merge conflicts is because the minified version of the generated CSS file. Every generated version of this file will have inevitable changes on one line so every PR will have conflicts to resolve. That being said, I understand the value of offering the .min.css right in the repo for the simple import use case.

**Comment by josephdburdick** [comment]
Let me know if there's anything you need from me on this. Once this is merged I look forward to using it in production.

**Comment by kazzkiq** [comment]
Hey, got kinda busy these days and just wanted to make sure everything worked properly with this change. Thanks for the PR! Merged.

**Pull request merged**
