### PR TITLE
bower manifest file

### PR DESCRIPTION
**Pull request by adamkirkwood**
Allow this package to be registered in Bower #11

### CODE REVIEW

**Comment by kazzkiq** [comment]
It seems Bower is no longer being actively supported by their team. Do you have any idea if we can still add stuff to it? I don't use Bower so I have no clue about its current state.

More info:
https://twitter.com/nachocoloma/status/663622545162280960
https://www.grobmeier.de/bower-github-community-18112015.html

**Comment by ciscoo** [comment]
I think npm would be a better option than bower. There is already a `package.json` in the project. Assuming all the neccessary fields are there and correct, simply run `npm publish`.

**Comment by kazzkiq** [comment]
@ciscoo It isn't documented yet, but the project is already published at npm.

To install: `npm install balloon-css`

**Comment by adamkirkwood** [comment]
@kazzkiq @ciscoo You guys are absolutely right. I also now believe Bower is no longer maintained.

NPM.js FTW!

**Pull request closed without merging**
