### PR TITLE
add gulp:

### PR DESCRIPTION
**Pull request by marcobiedermann**
- add package.json
- add gulp task
- compile scss
- change file structure

### CODE REVIEW

**Comment by davesnx** [comment]
I would prefer not use gulp for that, It's just add as a gem or npm dependency and run

``` bash
sass src/balloon.scss dist/ballon.css 
```

and another for the minification:

``` bash
sass src/balloon.scss dist/ballon.min.css --style compressed
```

Do you have any preference @kazzkiq?
Have a npm package that runs before a git push or a npm pre prublish or have a gulp task?

**Comment by kazzkiq** [comment]
I think the best approach for this would be using npm built-in tasks feature. I will publish the project on npm with a `build` task and proper dependencies to make easier for people to compile and test Balloon.css.

**Comment by kazzkiq** [comment]
Done. Check commit 000d729 for details.

`package.json` added. If there is intent on compiling the `.scss` file just run `npm install && npm run build` after cloning the repo.

If you want to keep compiling on file changes (useful for development) use the command `watch` instead of `build`.

**Comment by kazzkiq** [comment]
So

**Pull request closed without merging**
