### PR TITLE
put content in after instead of before for accessibility

### PR DESCRIPTION
**Pull request by lukehaas**
Currently you have the content of the tooltip in the before element. This isn't great for accessibility as people using screen readers will hear the content of the tooltip before hearing the inline text of the button etc. 
I've just made a simple change to reverse the styling of the before and after pseudo elements. It works just the same visually, but now screen reader users will know what the tooltip text relates to.

### CODE REVIEW

**Comment by kazzkiq** [comment]
@lukehaas Thanks for the contribution! However the project now uses both SASS and LESS as source files. As both should always stay in sync, do you think you could also port your code to the LESS version too?

**Comment by lukehaas** [comment]
Thanks, I've now applied those updates to the less file as well.

**Comment by lukehaas** [comment]
@kazzkiq I've brought in you latest updates so this is all still good to go in

**Comment by kazzkiq** [comment]
Perfect. Thanks!

**Pull request merged**
