### PR TITLE
Fix line break for multiple lines

### PR DESCRIPTION
**Pull request by devfake**
There is an problem with the current `data-balloon-break`. If there are multiple line breaks, it does not work with `white-space: normal`:

https://jsfiddle.net/7d6n63r4/1/

Change it to `pre-wrap` and it works fine:

https://jsfiddle.net/7d6n63r4/2/

Testet in Chrome and Firefox.

### CODE REVIEW

**Comment by kazzkiq** [comment]
Nice catch. However there were other changes in the meanwhile fixing other bugs and it seems those fixes generated some conflicts with your PR. Could you please fix this conflicts so I can accept your Pull Request? Thanks!

**Comment by devfake** [comment]
Done :) I had to change the cascade for `data-balloon-break`.

**Comment by ekatherina** [comment]
I tried https://jsfiddle.net/7d6n63r4/1/ and https://jsfiddle.net/7d6n63r4/2/ - It doesn't work.
I test in Chrome  50.0.2661.94 m.

**Comment by devfake** [comment]
The `before` pseudo element is changed to `after` in the new balloon version. This works: https://jsfiddle.net/7d6n63r4/3/

**Comment by kazzkiq** [comment]
Apparently, PR #48 fixed this.

**Pull request closed without merging**
