### PR TITLE
Apply transition delay to ease animation effect.

### PR DESCRIPTION
**Pull request by josephdburdick**
Currently when triggering a balloon the animation executes instantly. This isn't the _best_ experience because often times the hover "hit area" is smaller than users think they are, causing the balloon to shutter in and out until the pointer device settles within the invisible boundary. The fix is simple: use an animation delay of .18s, the same as the animation duration itself, to improve the chances of a smooth transition from beginning to end. It is definitely an improvement when hovering over multiple balloon triggers near each other.

### CODE REVIEW

**Comment by josephdburdick** [comment]
Accidentally added a few unnecessary files, will resend.

**Comment by kazzkiq** [comment]
Interesting, this would definitely help improve usability. Could you please just fix the conflicts so I can merge this PR?

**Comment by josephdburdick** [comment]
Sure, no problem @kazzkiq, all conflicts resolved.

**Comment by kazzkiq** [comment]
Great, thanks!

**Pull request merged**
